CREATE TABLE `user` (
  `USER_ID` char(7) COLLATE utf8_bin NOT NULL COMMENT 'ユーザーID',
  `PASSWORD` char(64) COLLATE utf8_bin NOT NULL COMMENT 'パスワード',
  `ROLE_ID` char(3) COLLATE utf8_bin NOT NULL COMMENT 'ロールID',
  `AFFILIATION` int(11) NOT NULL COMMENT '所属',
  `POSITION` int(11) NOT NULL COMMENT '役職',
  `PASSWORDLAST_CHANGE_DATE` date NOT NULL COMMENT 'パスワード最終更新日',
  `PASSWORD_MISS_COUNT` int(11) NOT NULL COMMENT 'パスワード誤入力回数',
  `PASSWORD_INITIAL_FLAG` int(11) NOT NULL COMMENT 'パスワード初期フラグ',
  `DELETE_FLAG` int(11) NOT NULL COMMENT '削除フラグ',
  `REGIST_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '登録者',
  `REGIST_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
  `UPDATE_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '更新者',
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `VERSION` int(11) NOT NULL DEFAULT '0' COMMENT 'バージョン',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin

CREATE TABLE `BREAK_TIME` (
  `WORK_TIME_CD` int(11) NOT NULL COMMENT '勤務帯コード',
  `BREAK_START_TIME` time NOT NULL COMMENT '休憩開始時刻',
  `BREAK_END_TIME` time NOT NULL COMMENT '休憩終了時刻',
  `REGIST_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '登録者',
  `REGIST_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
  `UPDATE_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '更新者',
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `VERSION` int(11) DEFAULT NULL COMMENT 'バージョン',
  PRIMARY KEY (`WORK_TIME_CD`,`BREAK_START_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='休憩時間'

CREATE TABLE `CUSTOMER` (
  `CUSTOMER_ID` int(11) NOT NULL COMMENT '顧客ID',
  `CUSTOMER_NAME` varchar(255) COLLATE utf8_bin NOT NULL COMMENT '顧客名',
  `REGIST_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '登録者',
  `REGIST_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
  `UPDATE_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '更新者',
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `VERSION` int(11) DEFAULT NULL COMMENT 'バージョン',
  PRIMARY KEY (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='顧客'

CREATE TABLE `HORIDAY` (
  `DATE` date NOT NULL COMMENT '日付',
  `HORIDAY_NAME` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '祝日名',
  `REGIST_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '登録者',
  `REGIST_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
  `UPDATE_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '更新者',
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `VERSION` int(11) DEFAULT NULL COMMENT 'バージョン',
  PRIMARY KEY (`DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='祝日'

CREATE TABLE `JOIN_PROJECT` (
  `USER_ID` char(7) COLLATE utf8_bin NOT NULL COMMENT 'ユーザーID',
  `PROJECT_ID` int(11) NOT NULL COMMENT 'プロジェクトID',
  `START_DATE` date NOT NULL COMMENT '開始日付',
  `END_DATE` date DEFAULT NULL COMMENT '終了日付',
  `REGIST_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '登録者',
  `REGIST_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
  `UPDATE_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '更新者',
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `VERSION` int(11) DEFAULT NULL COMMENT 'バージョン',
  PRIMARY KEY (`USER_ID`,`PROJECT_ID`,`START_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='参画プロジェクト'

CREATE TABLE `PROJECT` (
  `PROJECT_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'プロジェクトID',
  `PROJECT_NAME` varchar(255) COLLATE utf8_bin NOT NULL COMMENT 'プロジェクト名',
  `AFFILIATION` int(11) NOT NULL COMMENT '所属',
  `CUSTOMER_ID` int(11) NOT NULL COMMENT '顧客ID',
  `START_DATE` date DEFAULT NULL COMMENT '開始日',
  `END_DATE` date DEFAULT NULL COMMENT '終了日',
  `REGIST_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '登録者',
  `REGIST_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
  `UPDATE_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '更新者',
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `VERSION` int(11) DEFAULT NULL COMMENT 'バージョン',
  PRIMARY KEY (`PROJECT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='プロジェクト'

CREATE TABLE `TRANSPORTION_EXPENSE` (
  `USER_ID` char(7) COLLATE utf8_bin NOT NULL COMMENT 'ユーザーID',
  `WORK_DATE` date NOT NULL COMMENT '日付',
  `TRANSPORT_NUMBER` int(11) NOT NULL COMMENT '交通費通番',
  `TRANSEPORT_TYPE` int(11) NOT NULL COMMENT '交通手段',
  `ONE_WAY_ROUND_TYPE` int(11) NOT NULL COMMENT '片道往復',
  `RIDE_FROM` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '乗車',
  `RIDE_TO` varchar(100) COLLATE utf8_bin NOT NULL COMMENT '下車',
  `EXPENSE` int(11) NOT NULL COMMENT '金額',
  `DESTINATION` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '目的地',
  `REASON` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '理由',
  `REGIST_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '登録者',
  `REGIST_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
  `UPDATE_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '更新者',
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `VERSION` int(11) DEFAULT NULL COMMENT 'バージョン',
  PRIMARY KEY (`USER_ID`,`WORK_DATE`,`TRANSPORT_NUMBER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='交通費'

CREATE TABLE `WORK_TIME` (
  `USER_ID` char(7) COLLATE utf8_bin NOT NULL COMMENT 'ユーザーID',
  `WORK_DATE` date NOT NULL COMMENT '日付',
  `WORK_TIME_TYPE` int(11) NOT NULL COMMENT '勤務帯',
  `START_TIME` time DEFAULT NULL COMMENT '出社時刻',
  `END_TIME` time DEFAULT NULL COMMENT '退社時刻',
  `START_WORK_CODE` int(11) NOT NULL COMMENT '始業コード',
  `END_WORK_CODE` int(11) NOT NULL COMMENT '終業コード',
  `COMPENSATORY_ATTENDANCE_DATE` date DEFAULT NULL COMMENT '代休出日',
  `ATTENDANCE_CODE` int(11) NOT NULL COMMENT '出勤コード',
  `NOTES` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '備考',
  `HORIDAY_TYPE` int(11) NOT NULL COMMENT '休日種別',
  `REGIST_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '登録者',
  `REGIST_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
  `UPDATE_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '更新者',
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `VERSION` int(11) DEFAULT NULL COMMENT 'バージョン',
  PRIMARY KEY (`USER_ID`,`WORK_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='勤務時間'

CREATE TABLE `WORK_TIME_STATUS` (
  `USER_ID` char(7) COLLATE utf8_bin NOT NULL COMMENT 'ユーザーID',
  `WORK_MONTH` char(7) COLLATE utf8_bin NOT NULL COMMENT '稼働月',
  `STATUS` int(11) NOT NULL COMMENT 'ステータス',
  `REGIST_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '登録者',
  `REGIST_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
  `UPDATE_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '更新者',
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `VERSION` int(11) DEFAULT NULL COMMENT 'バージョン',
  PRIMARY KEY (`USER_ID`,`WORK_MONTH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='勤務時間ステータス'

CREATE TABLE `WORK_TIME_TYPE` (
  `WORK_TIME_CD` int(11) NOT NULL COMMENT '勤務帯コード',
  `WORK_TIME_NAME` varchar(255) COLLATE utf8_bin NOT NULL COMMENT '勤務帯名称',
  `START_TIME` time DEFAULT NULL COMMENT '始業時刻',
  `END_TIME` time DEFAULT NULL COMMENT '終業時刻',
  `LUNCH_BREAK_TIME` int(11) NOT NULL COMMENT '昼休憩時間',
  `LUNCH_BREAK_START_TIME` time NOT NULL COMMENT '昼休憩開始時刻',
  `LUNCH_BREAK_END_TIME` time NOT NULL COMMENT '昼休憩終了時刻',
  `FLEX_FLAG` int(11) NOT NULL COMMENT 'フレックスフラグ',
  `LEAGAL_HORIDAY` int(11) NOT NULL COMMENT '法定休日(曜日)',
  `HORIDAY` int(11) NOT NULL COMMENT '休日(曜日)',
  `HALF_DAY_OFF_LIMIT_TIME` time NOT NULL COMMENT '半休境界時刻',
  `DELETE_FLAG` int(11) NOT NULL COMMENT '削除フラグ',
  `REGIST_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '登録者',
  `REGIST_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
  `UPDATE_USER` char(7) COLLATE utf8_bin NOT NULL COMMENT '更新者',
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `VERSION` int(11) DEFAULT NULL COMMENT 'バージョン',
  PRIMARY KEY (`WORK_TIME_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='勤務帯'
